name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"   # key - имя ключа в github
      - run: chmod 600 "$HOME/.ssh/key"

      # Build (опционально)
      - run: npm ci          # если используется gulp и есть package.json
      - run: npm run build   # если в package.json есть script: build

      # Deploy   полный адрес до папки сайта - нужно быть очень внимательным, т.к. содержимое этой папки полностью перезатрется
      - run: rsync -e "ssh -p 20022 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . f59436@hostus01.fornex.org:/home/f59436/public_html/norveg
